resources:
- name: self-update-src
  type: git
  source:
    repository: https://github.com/sursmobil/concourse-self-update.git

- name: ci-src
  type: git
  source: ((src-repo))

# - name: self-update-docker
#   type: docker-image
#   source: ((docker-repo))

jobs:
- name: ci-update
  plan:
  - aggregate:
    - get: self-update-src
    - get: ci-src
      trigger: true
  - task: set-pipelines
    file: self-update-src/tasks/set-pipelines.yml
